# Generated by Django 4.2 on 2023-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0002_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.JSONField(default=[], verbose_name='URL-картинки'),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.JSONField(default=['Nizier193'], verbose_name='Список друзей'),
        ),
    ]
