# Generated by Django 4.2 on 2023-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0006_alter_person_about_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
